### ISSUE TITLE
demo mode shouldn't complicate opening other databases

### ISSUE THREAD

**Issue by nealmcb** [boydgreenfield/query#1]
Currently, calling `QueryDb(demo=True)` changes the environment of the process via the helpers.py setup_demo_env() code.  That means that subsequent calls to QueryDb to create new db objects work differently, confusing the user. 

E.g. when I subsequently ran `mydb = QueryDb(database="/tmp/global-messages-db.sqlite", drivername="sqlite")` I still got the demo database.

I suggest having demo=True set up the parameters for the demo in a way that doesn't affect the use of other databases.

Thanks!

**Comment by boydgreenfield** [comment]
Agreed. Fixing with a patch now.

**Comment by nealmcb** [comment]
Nice!  Thanks.

**Comment by boydgreenfield** [comment]
No problem. Note this bumps query to v0.1.4 and now requires/is tested with pandas v0.16 and SQLAlchemy v0.99.
