### ISSUE TITLE
CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?

### ISSUE THREAD

**Issue by nealmcb** [boydgreenfield/query#3]
QueryDB works on some of my sqlite tables, and is very cool!
But for most of them I get a traceback ending in

local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.pyc in visit_null(self, type_)
   2796         raise exc.CompileError("Can't generate DDL for %r; "
   2797                                "did you forget to specify a "
-> 2798                                "type on this Column?" % type_)
   2799 
   2800     def visit_type_decorator(self, type_):

CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?

E.g. sql from ipython itself (.ipython/profile_default/history.sqlite), zeitgeist, chrome, zotero, bedup, tabs organizer, etc.

**Comment by boydgreenfield** [comment]
@nealmcb – Shoot. Two quick follow-up questions:
- Do you have a sample sqlite DB you could make available that I can use to debug this? 
- And is this a new issue for you in v0.1.3 or also a problem with prior releases? (v0.1.3 requires a newer version of SQLAlchemy, and I'm wondering if the problem relates to that version change)

I'll try to reproduce and debug if not. Thanks.

**Comment by boydgreenfield** [comment]
Ah just now parsing your "e.g." clause there. Let me try with, e.g., the Chrome sqlite DB. :)

**Comment by webmaven** [comment]
Is this still an issue?

**Comment by boydgreenfield** [comment]
@webmaven I was not readily able to reproduce this last year, and should have closed this issue then. I'm going to do so now, but please comment if you do run into it and take a look.

**Comment by masete** [comment]
I beleieve the solution to this is here,

https://docs.sqlalchemy.org/en/13/core/ddl.html

Am still figuring out how to construct thou......
